version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80" # Maps port 8080 on the host to port 80 on the container
    volumes:
      - ./app:/var/www/html # Syncs your code with the container
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3307" # Expose MySQL on port 3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
